### ISSUE TITLE
Testing request: Gigabyte GA-X79-UP4

### ISSUE THREAD

**Issue by Pneumaticat** [nkht/me_removal#1]
I would like to test on my [Gigabyte GA-X79-UP4](https://www.gigabyte.com/Motherboard/GA-X79-UP4-rev-11#ov) motherboard.

- Current BIOS version: F7 (with me_cleaner run)
- Operating system: Linux (NixOS unstable 19.09)

My main question is whether the DualBIOS capabilities will protect me against a bad flash, as I do not have an external programmer to recover it if necessary.

**Comment by nkht** [comment]
It doesn't look like DualBIOS lets you switch the ROM manually, which isn't ideal. I can't say for sure whether it would protect you. If the Gigabyte BIOS reacts very badly to removed ME firmware it may not.

Because of that uncertainty, and because this board doesn't seem to have hardware flashing features, I would recommend having an external flasher available. You can of course still try without, but you may end up needing to buy one anyway. From pictures, you would probably also need a test clip, as the flash chips appear to be SOIC-8 packages soldered directly to the board. 

If you want to try this the first thing to do is figure out the current size of your ME region. If you didn't use me_cleaner's '-t' switch it should still be the default of 2084864 bytes. You can check that by opening your ROM file in [UEFITool](https://github.com/LongSoft/UEFITool/releases/tag/0.26.0), expanding "Intel image" and selecting the ME region. The size will be displayed in the information panel on the right.

**Comment by Pneumaticat** [comment]
Okay, thanks for the info! I currently don't have the resources to get a hardware flasher, and since this system is pretty important for me, I probably won't risk it this early into the testing phase ;)
